// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package comredhatrhsm

import (
	"context"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		}
	}
	return err
}

// Generated client method calls

type Ping_methods struct{}

func Ping() Ping_methods { return Ping_methods{} }

func (m Ping_methods) Call(ctx context.Context, c *varlink.Connection, locale_in_ string) (running_out_ bool, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, locale_in_)
	if err_ != nil {
		return
	}
	running_out_, _, err_ = receive(ctx)
	return
}

func (m Ping_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, locale_in_ string) (func(ctx context.Context) (bool, uint64, error), error) {
	var in struct {
		Locale string `json:"locale"`
	}
	in.Locale = locale_in_
	receive, err := c.Send(ctx, "com.redhat.rhsm.Ping", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (running_out_ bool, flags uint64, err error) {
		var out struct {
			Running bool `json:"running"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		running_out_ = out.Running
		return
	}, nil
}

func (m Ping_methods) Upgrade(ctx context.Context, c *varlink.Connection, locale_in_ string) (func(ctx context.Context) (running_out_ bool, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Locale string `json:"locale"`
	}
	in.Locale = locale_in_
	receive, err := c.Upgrade(ctx, "com.redhat.rhsm.Ping", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (running_out_ bool, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Running bool `json:"running"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		running_out_ = out.Running
		return
	}, nil
}

// Generated service interface with all methods

type comredhatrhsmInterface interface {
	Ping(ctx context.Context, c VarlinkCall, locale_ string) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyPing(ctx context.Context, running_ bool) error {
	var out struct {
		Running bool `json:"running"`
	}
	out.Running = running_
	return c.Reply(ctx, &out)
}

// Generated dummy implementations for all varlink methods

func (s *VarlinkInterface) Ping(ctx context.Context, c VarlinkCall, locale_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "com.redhat.rhsm.Ping")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "Ping":
		var in struct {
			Locale string `json:"locale"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.comredhatrhsmInterface.Ping(ctx, VarlinkCall{call}, in.Locale)

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `com.redhat.rhsm`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface com.redhat.rhsm

method Ping(locale: string) -> (
    running: bool
)
`
}

// Generated service interface

type VarlinkInterface struct {
	comredhatrhsmInterface
}

func VarlinkNew(m comredhatrhsmInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
